var g={},k=[],l=null,aa,n,ba,ca,p,da,ea,q,ha={},ia={},ja={};function ka(){try{return new XMLHttpRequest}catch(a){}try{return new ActiveXObject("Msxml2.XMLHTTP")}catch(a){}return new ActiveXObject("Microsoft.XMLHTTP")}function r(a){return a?document.createTextNode(a):null}function la(a,b){return b?2==b?ia[a+q]:ja[a]?ja[a]:a<q?"Port"+(a+1):a>=q+ea?"Port"+(a-ea+1):"SFP"+(a-q+1):ia[a]}function u(a,b){return v(document.createElement(a),r(b))}function w(a,b,c){a=u(a,c);b&&(a.className=b);return a}
function v(a,b){b&&a.appendChild(b);return a}function x(a){return document.getElementById(a)}function y(a,b,c){c=w("td",c);b&&(c.colSpan=b);return v(c,a)}function ma(a,b,c,d,e){var f=u("iframe");f.id=a;f.src=b;f.width=c+"%";f.height=d;f.frameBorder="0";e||(f.scrolling="no");return f}function na(a){var b=x(a);if(!b)return b;b=b.contentDocument;b||(b=document.frames[a].document);return b}function pa(a){return" "==a||"\r"==a||"\n"==a}
function qa(a){for(var b=0;b<a.length&&pa(a.charAt(b));)++b;for(var c=a.length-1;c>b&&pa(a.charAt(c));)--c;return a.substring(b,c+1)}function ra(a,b){for(var c=0;c<a.length-1&&"0"==a.charAt(c);)++c;a=a.substring(c);c=parseInt(a,b);return isNaN(c)?c:c.toString(b).toLowerCase()!=a.toLowerCase()?Number.NaN:c}function sa(a,b){for(var c="",d=0;d<b;++d)c+=a;return c}function ta(a){a=a.toString(16);return 1==a.length?"0"+a:a}
function ua(a){for(var b=[],c=0;256>c;++c)b[c]=c;var d=0;for(c=c=0;256>c;++c){d=d+a.charCodeAt(c%a.length)+b[c]&255;var e=b[c];b[c]=b[d];b[d]=e}c=d=0;b.fa=function(){c=c+1&255;d=d+b[c]&255;var a=b[c];b[c]=b[d];b[d]=a;return b[b[c]+b[d]&255]};return b}
function va(a,b){for(var c=[],d=0;d<b.length;++d)c.push(b.charCodeAt(d));c.push(0);for(d=0;d<a.length;++d)c.push(a.charCodeAt(d));for(;32>c.length;)c.push(0);for(""==b&&(b="*");16>b.length;)b+=b;b=b.substring(0,16);a=ua(b);for(d=0;64>d;++d)c[d&31]^=a.fa();a="";for(d=0;32>d;++d)a+=ta(c[d]);return a}function wa(a){a||(a=x("status"));a.innerHTML="";a.className="status empty"}function z(a,b){a||(a=x("status"));a.innerHTML=b;a.className="status notify"}
function A(a,b){a||(a=x("status"));a.innerHTML="ERROR:\u00a0"+b;a.className="status error"}function xa(a,b){a||(a=x("status"));a.className="status important";a.innerHTML=b}function B(a,b,c,d){if(b){for(var e=0;e<a.C.length;++e)if(a.C[e].ha==b){a.C.splice(e,1);break}c&&a.C.unshift({ha:b,name:d})}0==a.C.length?a.S||(z(a.status,"Pending changes"),a.A&&(a.A.className="btn"),a.D=!0):(A(a.status,'Invalid "'+a.C[0].name+'"'),a.A&&(a.A.className="disbtn"),a.D=!0);if(a.D&&a.b.onchange)a.b.onchange(a)}
function ya(a){a.C=[];a.A&&(a.A.className="disbtn");wa(a.status);a.D=!1;a.b.ma&&a.b.ma(a)}function za(a){var b=u("input");b.type="text";a&&(b.size=a);return b}function Aa(){var a=u("input");a.type="password";return a}function C(a,b,c){a=w("span","ro");a.id=b.id+c;return a}
C.m=function(a,b,c,d){var e=b[a.id];if(a.J){if(b[a.id]=e>>1,e&=1,a.O){var f=b[a.O];b[a.O]=f>>1;e|=(f&1)<<1}}else e&&"object"==typeof e&&(e=e.shift());a.u&&(e=a.ia&&void 0==a.u[e]?a.ia[e]:a.u[e]);a.scale&&(e/=a.scale);a.f&&(1E9<e?e=Math.round(e/1E9*100)/100+"G":1E6<e?e=Math.round(e/1E6*100)/100+"M":1E3<e?e=Math.round(e/1E3*100)/100+"k":e=Math.round(e));void 0==e&&(e=a.h);if(void 0===e||""===e)e="\u00a0";c[d]=e.toString();return 1};C.l=function(){return 1};
function Ba(a,b,c){for(var d in b)b[d].checked==c?a[d]?a[d]=null:b[d]=null:(b[d].checked=c,b[d].onclick(null));for(d in a)a[d]&&(a[d].checked=!c,a[d].onclick(null));return b}
function Ca(a){a.onmousedown=function(b){var c=b.clientX,d=b.clientY,e=0,f=0,h=!a.checked,m={};m[a.id]=a;m=Ba({},m,h);document.body.onmousemove=function(a){var b=a.clientX-c;var t=a.clientY-d;Math.abs(b)>Math.abs(t)?t=0:b=0;var R=Math.sign(b),Fa=Math.sign(t);if(e&&e!=R)b={};else if(f&&f!=Fa)b={};else{for(var Wa={},oa=0;oa<=Math.max(b*R,t*Fa);++oa){var fa=document.elementFromPoint(c+oa*R,d+oa*Fa);fa&&"INPUT"==fa.nodeName&&"checkbox"==fa.type&&(Wa[fa.id]=fa)}b=Wa}if(t=!e&&!f){t=b;R=0;for(var rb in t)t[rb]&&
++R;t=1<R}t&&(Math.abs(a.clientX-c)>Math.abs(a.clientY-d)?e=Math.sign(a.clientX-c):f=Math.sign(a.clientY-d));m=Ba(m,b,h)};document.body.onmouseup=function(){document.body.onmousemove=null;document.body.onmouseup=null;a.onmouseup=null};document.body.onmouseleave=function(){document.body.onmousemove=null;document.body.onmouseup=null;a.onmouseup=null};a.onmouseup=function(){a.checked=!a.checked}}}
function D(a,b,c){if(b.a)return C(0,b,c);var d=u("input");d.type=b.ca?"radio":"checkbox";d.id=b.id+c;d.name=b.id;d.checked=b.h||0;d.value=c;d.onclick=function(){B(a);if(b.onclick)b.onclick()};b.F&&(d.title=la(c));b.ca||Ca(d);return d}D.m=function(a,b,c,d,e){var f=b[a.id];void 0==f&&(f=a.h||0);c[d]=a.a?a.u?a.u[f&1]:f&1?la(e)+" ":"":f&1;b[a.id]=f>>1;return 1};D.l=function(a,b,c,d){b[a.id]=(b[a.id]||0)>>1|(c[d]?1<<a.i-1:0);return 1};
function Da(a,b,c){if(c)return null;c=u("span");for(var d=0;d<b.i;++d)v(c,D(a,b,d)),v(c,r(ja[d]?ja[d]:d<q?d+1:"SFP"+(d-q+1)));return c}Da.m=D.m;Da.l=D.l;function E(a,b,c){var d=u("select");d.id=b.id+c;for(var e in b.w)v(d,u("option",b.w[e]));d.onchange=function(){B(a);if(b.onchange)b.onchange()};return d}E.m=function(a,b,c,d){a=b[a.id];c[d]=void 0==a?0:a.length?a.shift():a;return 1};E.l=function(a,b,c,d){a=a.id;c=c[d];-1==c&&(c=0);void 0==b[a]?b[a]=c:(b[a].length||(b[a]=[b[a]]),b[a].push(c));return 1};
function F(a,b,c){if(b.a)return C(0,b,c);a=za(b.V||4);a.id=b.id+c;b.j&&(a.value=b.h||0);return a}F.m=function(a,b,c,d){var e=b[a.id];e&&e.length&&(e=e.shift());e||(e=0);b="";if(a.j||e!=(a.h||0))a.scale&&(e/=a.scale),a.X&&(e=Math.log(e)/Math.log(10)*10,e=Math.floor(1E3*e)/1E3),b=e.toString(a.N||10),a.f&&(1E9<e&&!(e%1E9)?b=e/1E9+"G":1E6<e&&!(e%1E6)?b=e/1E6+"M":1E3<b&&!(b%1E3)&&(b=e/1E3+"k"));""!=b&&a.width&&(e=a.width,b=b.toString(),b=b.length<e?sa("0",e-b.length)+b:b);""!=b&&a.o&&(b+=a.o);c[d]=b;return 1};
F.l=function(a,b,c,d){if(!a.a){c=qa(c[d]);var e=a.h||0;a.j&&!c.length&&(c=e.toString());if(0!=c.length){d=1;a.f&&(e=c.charAt(c.length-1).toLowerCase(),"k"==e?d=1E3:"m"==e?d=1E6:"g"==e?d=1E9:e=null,e&&(c=c.substring(0,c.length-1)));e=ra(c,a.N||10);if(isNaN(e))return 0;e*=d;a.scale&&(e*=a.scale);if(a.max&&e>a.max||a.min&&e<a.min||0>e)return 0}void 0==b[a.id]?b[a.id]=e:(b[a.id].length||(b[a.id]=[b[a.id]]),b[a.id].push(e));return 1}};function Ea(a,b,c){return C(0,b,c)}
Ea.m=function(a,b,c,d){(b=b[a.id])&&b.length&&(b=b.shift());b||(b=0);2147483648<=b&&(b-=4294967296);var e="";if(a.j||b!=(a.h||0))a.scale&&(b/=a.scale),e=b.toString(a.N||10);""!=e&&a.o&&(e+=a.o);c[d]=e;return 1};Ea.l=function(){return 1};function G(a,b,c){if(b.a)return C(0,b,c);a=za();c=[];G.m(b,{},c,0);a.value=c[0];return a}
G.m=function(a,b,c,d){b=b[a.id];b instanceof Array&&(b=b.shift());if(!b||12!=b.length||b==sa(a.h||"0",12)){if(void 0==a.P)return c[d]="",1;b=sa(a.h||"0",12)}a="";for(var e=0;12>e;e+=2)0<e&&(a+=":"),a+=b.substring(e,e+2);c[d]=a;return 1};
G.l=function(a,b,c,d){if(a.a)return 1;d=qa(c[d]);if(!d.length)return a.h&&(b[a.id]=sa(a.h,12)),1;c=[];for(var e=0,f=!1;e<d.length;)if(isNaN(parseInt(d.charAt(e),16)))if(" "==d.charAt(e))++e;else if(":"==d.charAt(e)){if(!f)return 0;f=!1;++e}else return 0;else f=1,e+1<d.length&&!isNaN(parseInt(d.charAt(e+1),16))&&(f=2),c.push(parseInt(d.substring(e,e+f),16)),e+=f,f=!0;if(6!=c.length)return 0;d="";for(e=0;e<c.length;++e)16>c[e]&&(d+="0"),d+=c[e].toString(16).toLowerCase();if(void 0!=a.P&&d==sa(a.P,12))return 0;
b[a.id]=d;return 1};function H(a,b,c){if(b.a)return C(0,b,c);a=za();a.id=b.id+c;return a}H.m=function(a,b,c,d){a=b[a.id]||0;b="";if(0!=a)for(var e=0;4>e;++e)0<e&&(b+="."),b+=a&255,a>>=8;c[d]=b;return 1};H.l=function(a,b,c,d){c=qa(c[d]);if(!c.length)return b[a.id]=0,1;c=c.split(".",4);if(1==c.length)return 0;2>=c.length&&c.splice(c.length-1,0,"0");3>=c.length&&c.splice(2,0,"0");for(var e=d=0;e<c.length;++e){var f=ra(c[e],10);if(isNaN(f)||0>f||255<f)return 0;d=d>>8&16777215|f<<24}b[a.id]=d;return 1};
function I(a,b,c){return b.a?C(0,b,c):za(16)}function Ga(a){for(var b="",c=0;c+1<a.length;c+=2){var d=parseInt(a.substring(c,c+2),16);if(!d)break;b+=String.fromCharCode(d)}return b}I.m=function(a,b,c,d){a=b[a.id];a instanceof Array&&(a=a.shift());c[d]=Ga(a);return 1};I.l=function(a,b,c,d){if(a.a)return 1;c=c[d].substring(0,a.R||16);d="";for(var e=0;e<c.length;++e)d+=ta(c.charCodeAt(e));void 0==b[a.id]?b[a.id]=d:(b[a.id]instanceof Array||(b[a.id]=[b[a.id]]),b[a.id].push(d));return 1};
function Ha(a,b,c){for(var d=u("span"),e=0;e<b.f.length;++e)v(d,b.f[e].t(a,b.f[e],c));return d}Ha.m=function(a,b,c,d){var e=0,f;for(f in a.f)e+=a.f[f].t.m(a.f[f],b,c,d+e);return e};Ha.l=function(a,b,c,d){var e=0,f;for(f in a.f){var h=a.f[f].t.l(a.f[f],b,c,d+e);if(0==h)return 0;e+=h}return e};Ha.V=function(a){return a.f.length};function J(a,b,c){return b.a?C(0,b,c):za()}
J.m=function(a,b,c,d){var e="",f=[],h;for(h in a.g){0<h&&(e+=a.s);if(0==a.g[h].t.m(a.g[h],b,f,0))return 0;e+=f[0]}b=e.lastIndexOf(a.s);b+a.s.length==e.length&&(e=e.substring(0,b));c[d]=e;return 1};J.l=function(a,b,c,d){if(a.a)return 1;c=c[d].split(a.s,a.g.length);for(d=0;d<c.length;++d)if(0==a.g[d].t.l(a.g[d],b,c,d))return 0;for(d=c.length;d<a.g.length;++d)if(0==a.g[d].t.l(a.g[d],b,[""],0))return 0;return 1};
function K(a,b,c){if(a.b.oa&&"TABLE"==b.nodeName){b=b.rows;for(var d=b.length;0<d&&"interlive"!=b[d-1].className;)--d;for(var e=0;e<d&&"interlive"!=b[e].className;)++e;for(var f=b[e].cells.length,h=1;h<f;++h)for(var m=e;m<d;++m)K(a,b[m].cells[h],c)}else for(m=0;m<b.childNodes.length;++m){d=b.childNodes[m];if("INPUT"==d.nodeName){if("file"==d.type)continue;"text"==d.type?c(d,"value",!0):c(d,"checked",!1)}else"SELECT"==d.nodeName?c(d,"selectedIndex",!1):"SPAN"==d.nodeName&&"ro"==d.className&&c(d,null,
!1);K(a,d,c)}}function L(a,b,c){for(var d=0;d<a.length;++d){var e=a[d];if("string"==typeof e.t)b&&c(e,0);else for(var f=0;f<e.i;++f)c(e,f)}}function Ia(a,b,c,d){c||(c=a.c);a.S=!0;var e=0;K(a,c,function(a,c){if(!d||!c)if(!c||a[c]!=b[e])if(a[c||"innerHTML"]=b[e],a.onchange)a.onchange(null);++e});a.S=!1}function Ja(a,b){b||(b=a.c);var c=[];K(a,b,function(a,b){c.push(b?a[b]:null)});return c}function Ka(a,b){b=0==b.t.l(b,{},[a.value],0);a.className=b?"error":"";return b}
function M(a,b,c){B(a,b,Ka(b,c),c.n)}function La(a,b,c){var d=b.value;b.onkeydown=function(){setTimeout(function(){d!=b.value&&(d=b.value,M(a,b,c))},1)};b.onchange=function(){d=b.value;M(a,b,c)};b.oncut=function(){d=b.value;M(a,b,c)};b.onpaste=function(){d=b.value;M(a,b,c)};b.A=function(){d=b.value;M(a,b,c)};b.oninput=function(){d=b.value;M(a,b,c)};Ka(b,c)}function Ma(a,b,c){var d=[];K(a,b,function(a,b,c){d.push(c?a:null)});var e=0;L(c,!1,function(b){d[e]&&La(a,d[e],b);e+=b.t.V?b.t.V(b):1})}
function Na(a,b){var c=b?"[":"{",d=!0,e;for(e in a){var f=a[e];d||(c+=",");d=!1;b||(c+=e+":");switch(typeof f){case "string":c+="'"+f+"'";break;case "number":f=(f>>4&268435455).toString(16)+(f&15).toString(16);1==(f.length&1)&&(f="0"+f);c+="0x"+f;break;case "object":c+=Na(f,!0);break;default:c+="x"}}return c+(b?"]":"}")}function Oa(a){for(var b="[",c=0;c<a.length;++c)1<b.length&&(b+=","),b+=Na(a[c]);return b+"]"}
function N(a,b,c){var d=ka();d.onreadystatechange=function(){4==d.readyState&&c(d.status)};d.open("POST",a,!0);d.setRequestHeader("Content-Type","text/plain");d.send(b)}function Pa(a,b){var c=[],d=0;L(a,!1,function(a,f){d+=a.t.m(a,b,c,d,f)});return c}function Qa(a,b){var c=0,d={};try{L(a,!1,function(a){var e=a.t.l(a,d,b,c);if(0==e)throw a;c+=e})}catch(e){return null}return d}
function Ra(a,b){ya(a);z(a.status,"Applying changes...");N(a.b.url,b,function(b){200==b?wa(a.status):0==b?A(null,"Lost connection"):A(a.status,"Could not apply changes")})}function Sa(a){var b=a.b;Ta();z(a.status,"Retrieving...");b.L=null;O(a,b.url,function(a,b){Ua(a,b)})}function P(a,b,c){b=w("a","btn",b);v(a,b);c&&(b.onclick=function(){for(var a=this;"TBODY"!=a.nodeName;)a=a.parentNode;c(a)});b.draggable=!1;b.c=function(){return!1};return b}
function Q(a,b){a.status=w("span","status");v(b,a.status)}function Va(a,b,c){var d=w("div","btns");if(c)return d;a.A=P(d,"Apply All");a.D||(a.A.className="disbtn");a.A.onclick=function(){var b=a.b,c=b.ba(b.v,b.save(a));c&&(Ra(a,b.W(c)),b.$&&b.$(c))};P(d,"Discard Changes",function(){Sa(a)});b||Q(a,d);return d}
function Xa(a,b,c){var d=Va(a,!0,!b);b&&null!=a.b.G&&P(d,"Sort",function(){B(a);var b=Ya(a);Za(b,a.b.G);$a(a,b)});P(d,b?"Append":"Insert",function(b){var c=ab(a,a.b.v);b.parentNode.insertBefore(c,b);l&&Ia(a,l,c);a.D||B(a)});b||P(d,"Cut",function(b){l=Ja(a,b);K(a,b,function(b){b.onchange&&B(a,b,!1)});b.parentNode.removeChild(b);B(a)});b||c||P(d,"Clear",function(b){l=Ja(a,b);b.parentNode.replaceChild(ab(a,a.b.v),b);B(a)});b&&Q(a,d);return d}
function Za(a,b){a.sort(function(a,d){var c=parseInt(a[b])||0,f=parseInt(d[b])||0;return c<f?-1:c>f?1:a[b]<d[b]?-1:a[b]>d[b]?1:0})}
function $a(a,b){null!=a.b.G&&Za(b,a.b.G);for(var c=a.c,d=0,e=0,f=null,h=0;h<c.childNodes.length&&"THEAD"==c.childNodes[h].nodeName;++h)++d;for(h=c.childNodes.length-1;0<=h&&"footer"==c.childNodes[h].className;--h)f=c.childNodes[h],++e;for(;c.childNodes.length-d-e<b.length;)h=ab(a,a.b.v,a.b.a),f?c.insertBefore(h,f):v(c,h);for(;c.childNodes.length-d-e>b.length;)c.removeChild(c.childNodes[c.childNodes.length-e-1]);for(h=0;h<b.length;++h)Ia(a,b[h],c.childNodes[h+d])}
function Ya(a){for(var b=a.c,c=[],d=0;d<b.childNodes.length-1;++d)b.childNodes[d]&&"THEAD"!=b.childNodes[d].nodeName&&"footer"!=b.childNodes[d].className&&c.push(Ja(a,b.childNodes[d]));return c}function bb(a,b){for(var c=[],d=0;d<b.length;++d)c[d]=Pa(a,b[d]);return c}function cb(a,b){for(var c=[],d=0;d<b.length;++d){var e=Qa(a,b[d]);if(!e)return null;c.push(e)}return c}
function ab(a,b,c){var d;d||(d=a.b.list?"interlive":"");var e=w("tbody",d);if("group"!=b[0].t){var f=u("tr");v(e,f);var h;L(b,!1,function(b,c){b.F&&c||(h=u("td"),v(f,h));v(h,b.t(a,b,c))});c||v(f,y(Xa(a,!1,!0)))}else{var m;L(b,!0,function(b,c){if("group"==b.t)v(e,f=w("tr",b.K||""));else if("string"==typeof b.t){var d;"buttons"==b.t?d=Xa(a,!1):d=u(b.t,b.na);v(f,v(y(null,b.span||1),d))}else c||(b.label?m=y(null,b.span,"lbl"):(b.ja?v(m,r(b.n)):v(f,y(r(b.n?b.n+":":""),b.span,"lbl")),m=y(null,b.span)),
v(f,m)),v(m,b.t(a,b,c)),b.o&&v(m,r(b.o))})}c||Ma(a,e,b);return e}function db(a,b,c){b=w("th","cat",b);b.colSpan=c;v(a,v(u("tr"),b))}function eb(a){var b=w("tr","heading");v(a,v(u("thead"),b));return b}function S(a,b){b=w("tbody",b);v(a,b);return b}
function fb(a,b){a.c.className="list";a.c.border=0;var c=a.b;$a(a,b);a.Z=Xa(a,!0);b=w("tr","match");c=c.v;for(var d=0,e=1;e<c.length&&"group"!=c[e].t;++e)d+=c[e].span||1,"static"!=c[e].t&&(d+=c[e].span||1);b=v(b,v(y(null,d),a.Z));v(S(a.c,"footer"),b);a.b.buttons&&a.b.buttons(a)}
function gb(a,b){a.c.className="table";var c=a.b,d=eb(a.c),e=0;L(c.v,!1,function(a,b){a.F&&b||(v(d,u("th",1<a.i&&!a.F?la(b,c.Y):a.n)),++e)});c.a||v(d,w("th","hd","\u00a0"));$a(a,b);c.a||v(S(a.c,"footer"),v(w("tr","btns"),y(Xa(a,!0),e+1,"btns")))}
function hb(a,b){var c=a.b,d=c.i||p;if(1<d&&!c.ka){var e=eb(a.c);v(e,u("th"));for(var f=0;f<d;++f)v(e,u("th",la(f,c.Y)))}var h=S(a.c),m,t;L(c.v,!0,function(b,d){if("group"==b.t)db(h,b.n,(c.i||p)+1);else{d||(v(h,m=w("tr","interlive")),v(m,u("th",ha[b.n]||b.n)));var e=b.t(a,b,d);if(e){if(b.H&&d<b.H||b.I&&d>=b.I)e.style.visibility="hidden";b.F&&d||(t=u("td"),v(m,t));v(t,e)}}});c.a||(v(T(h,d+1),Va(a)),Ma(a,a.c,c.v));Ia(a,b)}
function Ua(a,b,c){if(a){var d=a.b,e=a.c;for(ya(a);e.hasChildNodes();)e.removeChild(e.lastChild);a.c.className="table props";d.M(a,b);b=a.c;e=d.ga;for(var f=u("thead"),h=b.rows[0],m=0,t=0;t<h.cells.length;++t)m+=h.cells[t].colSpan;db(f,e||"",m);b.insertBefore(f,b.firstChild);if(d.onload)d.onload();d.refresh&&ib(a);c&&B(a)}}
function O(a,b,c){a&&a.j&&a.j.abort();var d=ka();a&&(a.j=d);d.onreadystatechange=function(){if(4==d.readyState){var b=d.status,f=d.responseText;a&&(a.j=null);if(200==b)try{var h=eval("("+f+")");a?c(a,a.b.da(a.b.v,h)):c(a,h)}catch(m){A(null,m)}else 0==b?A(null,"Lost Connection"):401==b?(x("logout").style.display="none",x("login").style.display="inline",A(null,"Wrong password")):A(null,"Could not retrieve data"),jb()}};d.open("GET",b,!0);d.send(null)}var U;
function kb(a){O(a,a.b.url,function(a,c){a.b.load(a,c,null,!0);U=null;ib(a)})}function ib(a){U||(U=setTimeout(function(){kb(a)},a.b.refresh))}function Ta(){U&&(clearTimeout(U),U=null)}function jb(){for(var a=x("content");a.hasChildNodes();)a.removeChild(a.lastChild);Ta()}function lb(a){this.b=a;this.c=u("table");this.c.cellSpacing=0;this.c.width="100%";this.S=this.D=!1;this.C=[];this.j=this.status=this.A=this.Z=null;this.B={}}
function mb(a){var b=x("tabs");for(var c=0;c<b.childNodes.length;++c)b.childNodes[c].className="inactive";for(c=0;c<k.length;++c){b=k[c];var d=b.b;b.j&&b.j.abort();d.L=null;b.D&&(d.L=d.save(b))}k=[];l=null;jb();x(a.id).className="active";for(c in a.U){d=a.U[c];b=new lb(d);k.push(b);var e=x("content");e&&v(e,b.c);d.L||!d.url?(e=d.L,d.L=null,Ua(b,e,!!e)):(z(null,"Retrieving..."),O(b,d.url,function(a,b){Ua(a,b)}))}}
function T(a,b){var c=w("div","btns");v(a,v(w("tr","btns"),y(c,b||6,"btns")));return c}function nb(a,b,c){b=b||"/reboot";z(a,c||"Rebooting...");Ta();N(b,"*",function(a){200==a?setTimeout(function(){window.location.reload()},3E3):A(null,"Lost connection")})}window.reboot=nb;
window.uploaded=function(){var a=document.getElementsByClassName("important")[0];a&&("#upgrade"==location.hash?O(null,"/sys.b",function(b,c){c.upgr?(z(a,"Upgraded"),nb(a)):A(a,"Upgrade failed - invalid firmware file")}):(z(a,"Restored"),nb(a)))};function ob(a,b,c,d){P(a,b,function(){nb(null,c,d)})}function V(a,b,c){var d=w("tr","interlive");v(d,u("th",b));v(a,v(d,y(c)))}
function pb(a){if(a.B.T.value!=a.B.ea.value)A(a.status,"New passwords do not match");else if(15<a.B.aa.value.length)A(a.status,"Bad old password");else if(15<a.B.T.value.length)A(a.status,"New password is too long");else{z(a.status,"Changing password...");var b={};b.pwd=va(a.B.T.value,a.B.aa.value);N("/!pwd.b",Na(b),function(b){200==b?wa(a.status):0==b?A(null,"Lost connection"):405==b?A(a.status,"Incorrect old password"):A(a.status,"Could not change password")})}}
function qb(a){var b=S(a.c);V(b,"Old Password",a.B.aa=Aa());V(b,"New Password",a.B.T=Aa());V(b,"Confirm Password",a.B.ea=Aa());b=T(b,2);P(b,"Change Password",function(){pb(a)});Q(a,b)}
function sb(a){var b=S(a.c);V(b,"Backup to Restore",ma("rframe","/upload.html",70,25));b=T(b,2);ob(b,"Reset Configuration","/reset","Resetting configuration...");P(b,"Save Backup",function(){window.open("backup.swb","Download")});P(b,"Restore Backup",function(){var b=na("rframe");""==b.getElementById("file").value?A(a.status,"no backup file was selected"):(Ta(),xa(a.status,"Restoring backup... (Please do not interrupt)"),b=b.getElementById("form"),b.action="/backup.swb",b.submit())});Q(a,b)}
function tb(a){a=S(a.c);a=T(a,2);a.style.padding="24 0 8 0";ob(a,"Reboot");aa.search("CRS")||ob(a,"Boot RouterOS","/bootros")}function ub(a,b,c){var d=ka();d.onreadystatechange=function(){4==d.readyState&&(200==d.status?c(d.response):c(null))};d.open("GET",a);null!=b&&(d.responseType=b);d.send()}
function vb(a){a=a.replace("beta",".b.");a=a.replace("rc",".c.");a=a.split(".");var b=a.pop()|0,c=a.shift()|0,d=a.shift()|0;"b"==a[0]?(d|=128,a.shift()):"c"==a[0]?(d|=64,a.shift()):d|=192;return 4294967296*(c<<16|d<<8|a[0]|0)+b}function wb(a){a=a.split(".");var b=1E3*parseInt(a.pop(),10);return a.join(".")+"&nbsp;<i>(built at "+(new Date(b)).toString()+")</i>"}
function xb(a,b){N("/pboot","*",function(c){if(200==c){c=new FormData;c.append("blob",b);var d=ka();d.onreadystatechange=function(){4==d.readyState&&(200==d.status?(xa(a.status,"Upgraded"),nb(a.status)):A(a.status,"Upgrade failed"))};d.open("POST","/upgrade");d.send(c)}else A(a.status,"upgrade failed")})}
function yb(a){var b=S(a.c),c=u("span"),d=u("span");V(b,"Current Installed Version",c);V(b,"Latest Available Version",d);c.innerHTML=wb(ca);var e="http://upgrade.mikrotik.com/swos2/"+ba.toLowerCase()+"/",f;b=S(a.c);db(b,"Changelog",2);v(b,v(w("tr","interlive"),y(ma("changelog","",100,400,!0),2)));b=T(b,2);var h=P(b,"Download & Upgrade",function(){z(a.status,"Retrieving...");ub(e+("swos-"+ba.toLowerCase()+"-"+f+".bin"),"blob",function(b){null==b?A(a.status,"Could not retrieve firmware"):(x("status").className=
"important",xa(a.status,"Upgrading... (Please do not interrupt)"),xb(a,b))})});h.className="disbtn";Q(a,b);ub(e+"LATEST",null,function(b){null==b?A(a.status,"Could not determine latest version,&nbsp;probably no internet connection.&nbsp;Use manual upgrade."):(b=qa(b),d.innerHTML=wb(b),vb(ca)<vb(b)?(f=b.split(".").slice(0,-1).join("."),h.className="btn",z(a.status,"New version is available for upgrade")):z(a.status,"SwOS is up to date"),ub(e+"CHANGELOG",null,function(a){var b=na("changelog");b&&(null!=
a?v(b.body,u("pre",a)):v(b.body,r("Could not retrieve changelog")))}))})}
function zb(a){var b=S(a.c);V(b,"File for Upgrade",ma("uframe","/upload.html",70,25));b=T(b,2);P(b,"Upgrade",function(){var b=na("uframe");""==b.getElementById("file").value?A(a.status,"no firmware was selected"):(x("status").className="important",xa(a.status,"Upgrading... (Please do not interrupt)"),N("/pboot","*",function(c){200==c?(c=b.getElementById("form"),c.action="/upgrade",c.submit()):A(a.status,"upgrade failed")}))});Q(a,b)}
function Ab(a){if(a=a.nm)for(var b=0;b<a.length;++b){var c=Ga(a[b]);ia[b]=c;ha["From Port"+(b+1)]="From "+c}}function Bb(a,b,c){for(var d=0;d<a.length;++d){var e=a[d];e.t||(e.t=C);null!=e.i?0==e.i&&(e.i=p):e.i=b;c&&(e.a=1);e.f&&Bb(e.f,b,e.a);e.g&&Bb(e.g,b,e.a)}}function W(a,b){var c=a.toLowerCase().replace(" ",""),d={};d.id=c;d.title=a.replace(" ","\u00a0");d.U=[];for(var e=1;e<arguments.length;++e)d.U.push(arguments[e]);g[c]=d}
function X(a,b,c,d){if("function"==typeof c){var e=c;c={};c.M=e}(c.url=a)&&"!"==a[0]&&(c.a=1);b&&(c.ga=b);c.list?(c.ba=cb,c.da=bb,c.save=Ya,c.load=$a,c.W=Oa):(c.ba=Qa,c.da=Pa,c.save=Ja,c.load=Ia,c.W=Na);if(3>=arguments.length)return c;c.v=[];for(e=3;e<arguments.length;++e)null!=arguments[e]&&c.v.push(arguments[e]);Bb(c.v,c.i||p,c.a);return c}function Cb(a,b,c,d){c.list=1;c.i=1;c.M=gb;return X.apply(null,arguments)}function Db(a,b,c,d){c.list=1;c.i=1;c.M=fb;return X.apply(null,arguments)}
function Eb(a,b,c,d){c.i||(c.i=1);c.ka=1;c.M=hb;return X.apply(null,arguments)}function Y(a,b,c,d){c.M=hb;return X.apply(null,arguments)}var Fb,Gb=!1;function Hb(a){Gb&&Fb!=a&&(Fb=a,a=a.substring(1),""!=a&&(location.hash=a),mb(g[a]||g.link))}window.frameLoaded=Hb;function Ib(){Hb(location.hash);setTimeout(Ib,200)}
function Jb(a,b){var c=u("li");c.id=a;b=u("a",b);b.href="#"+a;b.draggable=!1;b.c=function(){return!1};b.onclick=function(){var b=x("hf");b&&(b=b.contentWindow.document,window.XMLHttpRequest?b.open("text/html","replace"):b.open("javascript:'<html></html'"),b.write("<body onload=\"parent.frameLoaded('#"+a+"');\">"),b.close())};v(c,b);return c}
window.onloaded=function(){O(null,"/sys.b",function(a,b){n=Ga(b.brd);ca=Ga(b.ver)+"."+b.bld;O(null,"/link.b",function(a,b){b.prt&&(p=b.prt,ea=b.sfp,da=p-ea,q=void 0==b.sfpo?da:b.sfpo);Ab(b);O(null,"/sfp.b",function(a,b){b&&Ab(b);null==n&&(n="RB260GS");aa=n;n=n.replace("CRS","CSS");ba=n.split("-")[0];"CSS106-1G-4P-1S"==n&&(n="CSS106P");n=n.split("-")[0];ja[5]="SFP";p=6;ea=1;q=da=5;W("Link",Y("link.b","",{refresh:3E3,onload:Kb,Y:1,$:Ab},{n:"Enabled",id:"en",t:D},{n:"Name",id:"nm",t:I},{n:"Link Status",
id:"lnk",J:!0,u:["no link","<b>link on</b>"]},{n:"Auto Negotiation",id:"an",t:D,onclick:Kb},{n:"Speed",t:Ha,f:[{id:"spd",u:[10,100,1E3]},{id:"spdc",t:E,w:[10,100,1E3]}]},{n:"Full Duplex",t:Ha,f:[{id:"dpx",J:!0,u:["no","yes"]},{id:"dpxc",t:D}]},{n:"Flow Control",id:"fct",t:D},Z({n:"PoE",t:"group"}),Z({n:"PoE Out",id:"poe",t:E,w:["off","auto","on","calibr"],H:1,I:5}),Z({n:"PoE Priority",id:"prio",t:E,w:["1","2","3","4"],H:1,I:5}),Z({n:"PoE Status",id:"poes",H:1,I:5,u:{0:"disabled",15:"overload",16:"powered on",
10:"short circuit",6:"voltage too low",14:"current too low",7:"power cycle"},h:"waiting for load"}),Z({n:"PoE Current",id:"curr",t:F,a:1,H:1,I:5,o:"mA"}),Z({n:"PoE Power",id:"pwr",t:F,a:1,H:1,I:5,o:"W",scale:1E3})));W("SFP",Eb("sfp.b","",{refresh:1E3,a:1},{n:"Vendor",id:"vnd",t:I},{n:"Part Number",id:"pnr",t:I},{n:"Revison",id:"rev",t:I},{n:"Serial",id:"ser",t:I},{n:"Date",id:"dat",t:I},{n:"Type",id:"typ",t:I,R:32},{n:"Status",t:"group"},{n:"Temperature",id:"tmp",t:Ea,o:"C",h:-128},{n:"Voltage",id:"vcc",
t:F,o:"V",scale:1E4},{n:"Tx Bias",id:"tbs",t:F,o:"mA",scale:500},{n:"Tx Power",id:"tpw",t:F,o:"dBm",scale:1E4,X:1},{n:"Rx Power",id:"rpw",t:F,o:"dBm",scale:1E4,X:1}));W("Forwarding",Y("fwd.b","Forwarding",{},{n:"From Port1",id:"fp1",t:D},{n:"From Port2",id:"fp2",t:D},{n:"From Port3",id:"fp3",t:D},{n:"From Port4",id:"fp4",t:D},{n:"From Port5",id:"fp5",t:D},{n:"From Port6",id:"fp6",t:D},{n:"Port Lock",t:"group"},{n:"Port Lock",id:"lck",t:D},{n:"Lock On First",id:"lckf",t:D},{n:"Port Mirroring",t:"group"},
{n:"Mirror Ingress",id:"imr",t:D},{n:"Mirror Egress",id:"omr",t:D},{n:"Mirror To",id:"mrto",t:D,ca:1},{n:"Bandwidth Limit",t:"group"},{n:"Egress Rate",id:"or",t:F,f:1}));W("RSTP",Y("rstp.b","Per Port",{refresh:1E3},{n:"RSTP",id:"ena",t:D},{n:"Mode",id:"rstp",a:1,J:1,u:["STP","RSTP"]},{n:"Role",id:"role",u:["disabled","alternate","root","designated","backup"]},{n:"Root Path Cost",id:"rpc",t:F,a:1},{n:"Type",id:"p2p",O:"edge",J:1,u:["shared","point-to-point","edge","edge"]},{n:"State",id:"lrn",O:"fwd",
J:1,u:["discarding","learning","forwarding","forwarding"]}),Eb("sys.b","General",{refresh:1E3},{n:"Bridge Priority (hex)",t:F,id:"prio",j:1,N:16,width:4},{n:"Port Cost Mode",t:E,id:"cost",w:["short","long"]},{n:"Root Bridge",t:J,s:".",a:1,g:[{id:"rpr",t:F,N:16,j:1,width:4},{id:"rmac",t:G,P:1}]}));W("Statistics",Y("!stats.b","",{refresh:3E3},{n:"Rate",t:"group"},{n:"Rx Rate",id:"rrb",scale:.08,f:1},{n:"Rx Packet Rate",id:"rrp",scale:.64,f:1},{n:"Tx Rate",id:"trb",scale:.08,f:1},{n:"Tx Packet Rate",
id:"trp",scale:.64,f:1},{n:"Rx",t:"group"},{n:"Bytes",id:"rb"},{n:"Total Packets",id:"rtp"},{n:"Unicasts",id:"rup"},{n:"Broadcasts",id:"rbp"},{n:"Multicasts",id:"rmp"},{n:"64",id:"r64"},{n:"65-127",id:"r65"},{n:"128-255",id:"r128"},{n:"256-511",id:"r256"},{n:"512-1023",id:"r512"},{n:"1024-1518",id:"r1k"},{n:"1519-max",id:"rmax"},{n:"Tx",t:"group"},{n:"Bytes",id:"tb"},{n:"Total Packets",id:"ttp"},{n:"Unicast Packets",id:"tup"},{n:"Broadcasts",id:"tbp"},{n:"Multicasts",id:"tmp"},{n:"64",id:"t64"},{n:"65-127",
id:"t65"},{n:"128-255",id:"t128"},{n:"256-511",id:"t256"},{n:"512-1023",id:"t512"},{n:"1024-1518",id:"t1k"},{n:"1519-max",id:"tmax"}));W("Errors",Y("!stats.b","",{refresh:3E3},{n:"Rx",t:"group"},{n:"Pauses",id:"rpp"},{n:"Total Errors",id:"rte"},{n:"FCS Errors",id:"rfcs"},{n:"Align Errors",id:"rae"},{n:"Runts",id:"rr"},{n:"Fragments",id:"fr"},{n:"Too Long",id:"rtl"},{n:"Overflows",id:"rov"},{n:"Tx",t:"group"},{n:"Pauses",id:"tpp"},{n:"Total Errors",id:"tte"},{n:"Underruns",id:"tur"},{n:"Too Long",
id:"ttl"},{n:"Collisions",id:"tcl"},{n:"Excessive Collisions",id:"tec"},{n:"Multiple Collisions",id:"tmc"},{n:"Single Collisions",id:"tsc"},{n:"Excessive Deferred",id:"ted"},{n:"Deferred",id:"tdf"},{n:"Late Collisions",id:"tlc"}));W("VLAN",Y("fwd.b","",{},{n:"Ingress",t:"group"},{n:"VLAN Mode",id:"vlan",t:E,w:["disabled","optional","enabled","strict"]},{n:"VLAN Receive",id:"vlni",t:E,w:["any","only tagged","only untagged"]},{n:"Default VLAN ID",id:"dvid",t:F,j:1,min:1,max:4095},{n:"Force VLAN ID",
id:"fvid",t:D},{n:"Egress",t:"group"},{n:"VLAN Header",id:"vlnh",t:E,w:["leave as is","always strip","add if missing"]}));W("VLANs",Cb("vlan.b","",{G:0},{n:"VLAN ID",t:F,id:"vid",j:1,min:1,max:4095},{n:"IVL",t:D,id:"ivl"},{n:"IGMP Snooping",t:D,id:"igmp"},{n:"Port",t:E,id:"prt",h:0,i:p,w:["leave as is","always strip","add if missing","not a member"]}));W("Hosts",Cb("host.b","Static Hosts",{G:p+0},{n:"Port",t:D,id:"prt",h:1,i:p},{n:"MAC",t:G,id:"adr",P:0},{n:"VLAN ID",t:F,id:"vid",min:1,max:4095},
{n:"Drop",t:D,id:"drp"},{n:"Mirror",t:D,id:"mir"}),Cb("!dhost.b","",{refresh:5E3,G:0},{n:"Port",id:"prt",u:ia},{n:"MAC",t:G,id:"adr",h:"x"},{n:"VLAN ID",t:F,id:"vid"}));W("IGMP Groups",Cb("!igmp.b","",{refresh:5E3,G:0},{n:"Group Address",t:H,id:"addr"},{n:"VLAN",t:F,id:"vlan"},{n:"Member Ports",id:"prts",t:D,F:1,i:p}));W("SNMP",Eb("snmp.b","",{},{n:"Enabled",t:D,id:"en"},{n:"Community",t:I,id:"com",R:32},{n:"Contact Info",t:I,id:"ci",R:32},{n:"Location",t:I,id:"loc",R:32}));W("ACL",Db("acl.b","",
{},{t:"group",K:"match"},{n:"From",t:D,id:"frm",i:p,h:1,F:1},{t:"buttons",span:8},{t:"group",K:"match"},{n:"MAC Src",t:J,s:"/",g:[{t:G,id:"smac"},{t:G,id:"smsk",h:"f"}]},{n:"MAC Dst",t:J,s:"/",span:2,g:[{t:G,id:"dmac"},{t:G,id:"dmsk",h:"f"}]},{n:"Ethertype",t:F,id:"et",N:16},{t:"span",span:2,na:"hex"},{t:"group",K:"match"},{n:"VLAN",t:E,id:"vlan",w:["any","present","not present"]},{n:"VLAN ID",t:J,s:"-",span:2,g:[{t:F,id:"vidl",max:4095},{t:F,id:"vidh",max:4095}]},{n:"Priority",t:F,id:"prio",max:7,
h:8},{t:"span",span:2},{t:"group",K:"match"},{n:"IP Src",t:J,s:":",g:[{t:J,s:"/",g:[{t:H,id:"sip"},{t:F,id:"sipm",max:32}]},{t:J,s:"-",g:[{t:F,id:"sptl",max:65535},{t:F,id:"spth",max:65535}]}]},{n:"IP Dst",t:J,s:":",span:2,g:[{t:J,s:"/",g:[{t:H,id:"dip"},{t:F,id:"dipm",max:32}]},{t:J,s:"-",g:[{t:F,id:"dptl",max:65535},{t:F,id:"dpth",max:65535}]}]},{n:"Protocol",t:F,id:"prot",max:255},{n:"DSCP",t:F,id:"dscp",max:63,h:64},{t:"group",K:"act"},{t:D,id:"snde",label:1},{n:"Redirect To",t:D,id:"snd",ja:1,
i:p,F:1},{o:"Mirror",t:D,id:"mirr",pa:0},{n:"Rate",t:F,f:1,id:"rate"},{n:"Set VLAN ID",t:F,id:"svid",max:4095},{n:"Priority",t:F,id:"spri",max:7,h:8},{t:"group"},{t:"hr",span:10}));W("System",Eb("sys.b","General",{refresh:1E3,onload:Lb},{n:"Address Acquisition",t:E,id:"iptp",w:["DHCP with fallback","static","DHCP only"],onchange:Lb},{n:"Static IP Address",t:H,id:"sip"},{n:"Identity",t:I,id:"id"},{n:"Allow From",t:J,s:"/",g:[{t:H,id:"alla"},{t:F,id:"allm",max:32}]},{n:"Allow From Ports",t:Da,id:"allp",
i:p},{n:"Allow From VLAN",t:F,id:"avln",max:4095},{n:"Watchdog",t:D,id:"wdt"},{n:"Independent VLAN Lookup",t:D,id:"ivl"},{n:"IGMP Snooping",t:D,id:"igmp"},{n:"Mikrotik Discovery Protocol",t:D,id:"dsc"},Z({n:"Port1 PoE In Long Cable",t:D,id:"lcbl"}),{n:"MAC Address",t:G,id:"mac",a:1},{n:"Serial Number",t:I,id:"sid",a:1},{n:"Board Name",t:I,id:"brd",a:1},Z({n:"Health",t:"group"}),Z({n:"Voltage",t:F,id:"volt",o:"V",a:1,scale:1E3}),Z({n:"Temperature",t:Ea,id:"temp",j:1,o:"C",a:1})),X(null,"Password Change",
qb),X(null,"Backup",sb),X(null,"",tb));W("Upgrade",X(null,"Firmware",yb),X(null,"Manual Upgrade",zb));setTimeout(Ib,10);if(a=x("tabs")){for(var c in g)g[c].la&&g[c].la!=n||v(a,Jb(g[c].id,g[c].title));Gb=!0}})})})};window.logout=function(){for(var a=0;a<k.length;++a){var b=k[a];b.j&&b.j.abort()}k=[];jb();N("/logout","*",function(){window.location.reload()})};window.login=function(){window.location.reload()};function Kb(){for(var a=0;a<p;++a){var b=x("an"+a).checked;x("spd"+a).style.display=x("dpx"+a).style.display=b||a>=da?"inline":"none";x("spdc"+a).style.display=x("dpxc"+a).style.display=b||a>=da?"none":"inline"}}function Lb(){x("sip0").disabled=2==x("iptp0").selectedIndex}function Z(a){return"CSS106P"==n?a:null};
